export const SURVEY_START = "SERVEY_START";
export const SURVEY_SUCCESS_RECEIVED = "SURVEY_SUCCESS_RECEIVED";
export const SURVEY_SUCCESS_CREATED = "SERVEY_SUCCESS_CREATED";
export const SURVEY_SUCCESS_UPDATED = "SERVEY_SUCCESS_UPDATED";
export const SURVEY_FAIL = "SURVEY_FAIL";
export const SURVEY_USERNAME_SET = "SURVEY_USERNAME_SET";
export const SURVEY_SUCCESS_QUESTIONS_RECEIVERD =
  "SURVEY_SUCCESS_QUESTIONS_RECEIVERD";
export const STATISTICS_START = "STATISTICS_START";
export const STATISTICS_SUCCESS = "STATISTICS_SUCCESS";
export const STATISTICS_FAIL = "STATISTICS_FAIL";
export const SIMPLE_STATISTICS_SUCCESS = "SIMPLE_STATISTICS_SUCCESS";

export const GENERAL_COLOR_CHANGED = "GENERAL_COLOR_CHANGED";
export const GENERAL_LANGUAGE_SET = "GENERAL_LANGUAGE_SET";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_GET_USER_DETAIL = "AUTH_GET_USER_DETAIL";
