# Generated by Django 2.2.3 on 2019-10-07 07:32

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import survey.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('name_fa', models.CharField(blank=True, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('ask', models.CharField(blank=True, max_length=200, null=True)),
                ('ask_fa', models.CharField(blank=True, max_length=200, null=True)),
                ('ask_en', models.CharField(blank=True, max_length=200, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('point', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('analyze', jsonfield.fields.JSONField(null=True)),
                ('analyze_fa', jsonfield.fields.JSONField(null=True)),
                ('analyze_en', jsonfield.fields.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('name_fa', models.CharField(blank=True, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('realAnswers', jsonfield.fields.JSONField(null=True)),
                ('uuid', models.CharField(blank=True, default=survey.models.generate_uuid, max_length=32, null=True)),
                ('lang', models.CharField(default='fa', max_length=10)),
                ('password', models.CharField(default='1234', max_length=256)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('questions', models.ManyToManyField(to='survey.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='target',
            field=models.ManyToManyField(to='survey.Target'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='choices/')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('total_correct', models.IntegerField(null=True)),
                ('free', models.BooleanField(default=False)),
                ('answers', jsonfield.fields.JSONField(null=True)),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
        ),
    ]
