# Generated by Django 2.2.3 on 2019-08-13 16:27

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='uuid',
            field=models.CharField(blank=True, default=survey.models.generate_uuid, editable=False, max_length=32, null=True),
        ),
    ]
