# Generated by Django 2.2.3 on 2019-10-21 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0002_auto_20191020_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='password',
        ),
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program', to=settings.AUTH_USER_MODEL),
        ),
    ]
