# Generated by Django 2.2.3 on 2019-09-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190921_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='lang',
            field=models.CharField(default='fa', max_length=10),
        ),
    ]
