# Generated by Django 2.2.3 on 2019-10-21 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20191021_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Target'),
        ),
    ]
