# Generated by Django 2.2.3 on 2019-10-22 08:15

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_survey_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answers',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='realAnswers',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
