# Generated by Django 2.2.3 on 2019-09-22 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_survey_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='upload',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
    ]
