# Generated by Django 2.2.3 on 2019-09-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20190922_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
