# Generated by Django 2.2.3 on 2019-09-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20190922_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='sex',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='target',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
