# Generated by Django 2.2.3 on 2019-09-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20190922_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='target',
        ),
        migrations.AddField(
            model_name='question',
            name='target',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='target_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='target_fa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
