# Generated by Django 2.2.3 on 2019-09-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20190922_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='point',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='sex',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
