# Generated by Django 2.2.3 on 2019-09-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20190923_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='target_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='target_fa',
        ),
        migrations.RemoveField(
            model_name='question',
            name='target',
        ),
        migrations.AddField(
            model_name='question',
            name='target',
            field=models.ManyToManyField(to='survey.Target'),
        ),
    ]
