# Generated by Django 2.2.3 on 2019-09-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20190923_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='target',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
