# Generated by Django 2.2.3 on 2019-09-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='target',
            field=models.ManyToManyField(to='survey.Target'),
        ),
        migrations.AddField(
            model_name='target',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='name_fa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
