# Generated by Django 2.2.3 on 2019-09-28 14:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20190923_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='analyze',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
