# Generated by Django 2.2.3 on 2019-09-28 14:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_question_analyze'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='analyze_en',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='analyze_fa',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
