# Generated by Django 2.2.3 on 2019-09-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20190928_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='password',
            field=models.CharField(default='1234', max_length=256),
        ),
    ]
