# Generated by Django 2.2.3 on 2019-10-02 23:23

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20190930_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='survey',
            name='uuid',
            field=models.CharField(blank=True, default=survey.models.generate_uuid, max_length=32, null=True),
        ),
    ]
